#config.yaml

paths:
  model_address: ~/models/state-spaces/mamba-130m
  store_address: ~/pruned_models/model
params:
  model_param: 130m
  seed: 0
  nsamples: 32
  seqlen: 2048
  sparsity_ratio: 0.5
  device_num: 'cuda:3'
  dtype: bfloat16
prune:
  prune_opt: sparsegpt
  prune_in_proj: True
  prune_conv1d: True
  prune_x_proj: True
  prune_dt_proj: True
  prune_A_log: True
  prune_out_proj: True
  ssm_state: null
  prune_n: 0